POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWlsQGNyZXNjZW50Y2l0eS5jb20iLCJleHAiOjE3MDUwMTg5OTIsInVzZXJJZCI6MX0.DzoThT-iPL--V5D5cKanXi05m79Vpe1e1hMvob1hUg4

{
    "name": "Test event 2",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}